function Material = emptymaterial_mfemm ()

    % Magnetics properties
    Material = struct ('Name', {}, ...
                       'Mu_x', {}, ...
                       'Mu_y', {}, ...
                       'H_c', {}, ...
                       'H_cAngle', {}, ...
                       'J_re', {}, ...
                       'J_im', {}, ...
                       'Sigma', {}, ...
                       'd_lam', {}, ...
                       'Phi_h', {}, ...
                       'Phi_hx', {}, ...
                       'Phi_hy', {}, ...
                       'LamType', {}, ...
                       'LamFill', {}, ...
                       'NStrands', {}, ...
                       'WireD', {}, ...
                       'BHPoints', {}, ...
                       'Density', {}, ...
                       'Kx', {}, ... % thermal proerties start here
                       'Ky', {}, ...
                       'Kt', {}, ...
                       'qv', {}, ...
                       'TKPoints', {} );

end