function [vars, extra_mex_args] = mmake_check_cross (winmexlibdir, vars)

    assert ( ~isempty (winmexlibdir), ...
             sprintf ( ['W64CrossBuild is true, but W64CrossBuildMexLibsDir is empty.\n', ...
                        'You must supply the location of the windows mingw64 windows libraries'] ) ...
           );

    assert ( all ( [ exist(fullfile (winmexlibdir, 'libmex.a'), 'file'), ...
                     exist(fullfile (winmexlibdir, 'libmx.a'), 'file'), ...
                     exist(fullfile (winmexlibdir, 'libmat.a'), 'file') ] ), ...
             'One of libmex.a, libmx.a or libmat.a was not found in %s', ...
             winmexlibdir );

    cross_full_path = mmake.cross.cross_prefix_full_path ('x86_64-w64-mingw32.static');

    vars.COMPILER = ['"', cross_full_path, '-gcc"'];

    extra_mex_args = ['-L"', options.W64CrossBuildMexLibsDir, '"'];
        
        
end