function ansfile = fsolver(filename, verbose, deletemeshfiles)
% solves a finite element problem described by a .fem file and which has
% already been meshed using fmesher
%
% Syntax
%
% ansfile = fsolver(filename)
% ansfile = fsolver(filename, verbose)
% ansfile = fsolver(filename, verbose, deletemeshfiles)
%
% Input
%
%  filename - string containing either the full path of the .fem file to be
%    solved, which must already have been meshed by fmesher, or the full
%    path, but without the .fem extension.
%
%  verbose - optional flag determining how much output is printed by
%    fsolver. Set to true to display output, or false to prevent display.
%    Defaults to true.
%
%  deletemeshfiles - optional true or false flag determining whether to
%    delete mesh files after loading them from disk.
%
% Output
%
%  ansfile - string containing the name of the solution file generated by
%    fsolver
%

    if nargin < 2
        verbose = true;
    end
    
    if nargin < 3
        deletemeshfiles = true;
    end
    
    % if present, strip the .fem extension to get the base file name for
    % mexfsolver
    if strcmpi(filename(end-3:end), '.fem')
        filename = filename(1:end-4);
    end
    
    if exist([filename, '.fem'], 'file') ~= 2
        error('The supplied filename location cannot be found.')
    end
    
    exts = {'.ele', '.node', '.pbc', '.edge'};
    
    missingfilestr = '';
    anymissing = false;
    % check for the existance of missing files
    for i = 1:numel(exts)
        if ~exist([filename, exts{i}], 'file')
            anymissing = true;
            missingfilestr = sprintf('%s%s\n', missingfilestr, [filename, exts{i}]);
        end
    end
    
    if anymissing
        error('The following required files were missing\n%sPerhaps you need to rerun fmesher?', missingfilestr);
    end

    mexfsolver(filename, double(verbose), double(deletemeshfiles));

    ansfile = [filename, '.ans'];
    
end