function ansfile = hsolver(filename, verbose, keepmesh)
% solves a finite element problem described by a .fem file and which has
% already been meshed using fmesher
%
% Syntax
%
% ansfile = hsolver(filename)
% ansfile = hsolver(filename, verbose)
% ansfile = hsolver(filename, verbose, deletemeshfiles)
%
% Input
%
%  filename - string containing either the full path of the .fem file to be
%    solved, which must already have been meshed by fmesher, or the full
%    path, but without the .fem extension.
%
%  verbose - optional flag determining how much output is printed by
%    hsolver. 
%
%  deletemeshfiles - optional flag determining whether to delete mesh files
%    after loading them from disk.
%
% Output
%
% ansfile - string containing the name of the solution file generated by
%  fsolver
%

    if nargin < 2
        verbose = true;
    end
    
    if nargin < 3
        keepmesh = false;
    end
    
    % if present, strip the .feh extension to get the base file name for
    % mexhsolver
    if strcmpi(filename(end-3:end), '.feh')
        filename = filename(1:end-4);
    end
    
    if exist([filename, '.feh'], 'file') ~= 2
        error('The supplied filename location cannot be found.')
    end
    
    exts = {'.ele', '.node', '.pbc', '.edge'};
    
    missingfilestr = '';
    anymissing = false;
    % check for the existance of missing files
    for i = 1:numel(exts)
        if ~exist([filename, exts{i}], 'file')
            anymissing = true;
            missingfilestr = sprintf('%s%s\n', missingfilestr, [filename, exts{i}]);
        end
    end
    
    if anymissing
        error('The following required files were missing\n%sPerhaps you need to rerun fmesher?', missingfilestr);
    end

    mexhsolver(filename, double (verbose), double (keepmesh));

    ansfile = [filename, '.anh'];
    
end