function [libluacomplex_sources, libluacomplex_headers] = getlibluasources ()


    libluacomplex_sources = { ...
        'femmcomplex.cpp', ...
        'lapi.cpp', ...
        'lauxlib.cpp', ...
        'lbaselib.cpp', ...
        'lcode.cpp', ...
        'ldblib.cpp', ...
        'ldebug.cpp', ...
        'ldo.cpp', ...
        'lfunc.cpp', ...
        'lgc.cpp', ...
        'liolib.cpp', ...
        'llex.cpp', ...
        'lmathlib.cpp', ...
        'lmem.cpp', ...
        'lobject.cpp', ...
        'lparser.cpp', ...
        'lstate.cpp', ...
        'lstring.cpp', ...
        'lstrlib.cpp', ...
        'ltable.cpp', ...
        'ltests.cpp', ...
        'ltm.cpp', ...
        'lundump.cpp', ...
        'lvm.cpp', ...
        'lzio.cpp', ...
        };
    
    libluacomplex_headers = { ...
    	'llimits.h', ...
    	'lopcodes.h', ...
    	'lua.h', ...
    	'luadebug.h', ...
    	'lualib.h', ...
        };
    
end