function libfemm_sources = getlibfemmsources ()

    libfemm_sources = { ...
        'femmconstants.cpp', ...
        'femmenums.cpp', ...
        'CArcSegment.cpp', ...
        'CBlockLabel.cpp', ...
        'CBoundaryProp.cpp', ...
        'CCircuit.cpp', ...
        'CCommonPoint.cpp', ...
        'CElement.cpp', ...
        'CAirGapElement.cpp', ...
        'CliTools.cpp', ...
        'CMaterialProp.cpp', ...
        'CMeshNode.cpp', ...
        'CNode.cpp', ...
        'CPointProp.cpp', ...
        'CSegment.cpp', ...
        'cspars.cpp', ...
        'cuthill.cpp', ...
        'feasolver.cpp', ...
        'FemmProblem.cpp', ...
        'FemmReader.cpp', ...
        'FemmStateBase.cpp', ...
        'femmversion.cpp', ...
        'fparse.cpp', ...
        'fullmatrix.cpp', ...
        'IntPoint.cpp', ...
        'LuaInstance.cpp', ...
        'PostProcessor.cpp', ...
        'spars.cpp', ...
        'stringTools.cpp', ... 
        };

end