#ifndef FEMMVERSION_H
#define FEMMVERSION_H

#define FEMM_FLAVOR "xfemm"
#define FEMM_VERSION_MAJOR 1
#define FEMM_VERSION_MINOR 6
#define FEMM_VERSION_PATCH 0

#define FEMM_VERSION_INT ( ( FEMM_VERSION_MAJOR * 100 + FEMM_VERSION_MINOR ) * 100 + FEMM_VERSION_PATCH )

#endif
